### ISSUE TITLE
SVZ - Skript funktioniert nicht mehr...

### ISSUE THREAD

**Issue by Kordupel** [michamilz/lokalplus#6]
Hallo, vielen Dank für die tolle Arbeit bisher. Offenbar gab es eine technische Umstellung bei der SVZ. Wird es eine entsprechende Anpassung des Skripts geben? Gruß AS

**Comment by michamilz** [comment]
Sieht gut aus. Am Wochenende kommt bestimmt ein Update.

**Comment by michamilz** [comment]
Der Link zur AMP Version wird wieder angezeigt.
